name: Azure Static Web Apps CI/CD

on:
  workflow_dispatch:
    inputs:
      spa_environment:
        description: 'Select SPA environment to deploy to'
        required: true
        type: choice
        options:
          - development
          - preview
  workflow_call:
    secrets:
      AZURE_STATIC_WEB_APPS_DEPLOYMENT_TOKEN_YELLOW_DUNE_0565BA100:
        required: true
    
jobs:
  build_and_deploy_job:
    environment: development
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
       id-token: write
       contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      # Build
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build

      # Deploy
      - name: Install Azure SWA
        run: npm install -g @azure/static-web-apps-cli
      - name: Deploy to '${{ inputs.spa_environment }}'
        run: swa deploy ./dist --deployment-token ${{ secrets.AZURE_STATIC_WEB_APPS_DEPLOYMENT_TOKEN_YELLOW_DUNE_0565BA100 }} --env ${{ inputs.spa_environment }}


