name: Azure Static Web Apps CI/CD

on:
  workflow_dispatch:
    inputs:
      environment:                # GitHub Environment name (for env-scoped secrets, approvals)
        description: 'GitHub Environment to target'
        required: true
        type: choice
        options:
          - development
          - preview
      swa_deploy_env:             # SWA deploy lane: production | preview
        description: 'SWA deploy target (production/preview)'
        required: true
        type: choice
        options:
          - production
          - preview
  workflow_call:
    inputs:
      environment:
        description: 'GitHub Environment to target'
        required: true
        type: string
      swa_deploy_env:
        description: 'SWA deploy target (production/preview)'
        required: true
        type: string
    secrets:
      AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_DUNE_0565BA100:
        required: true

jobs:
  build_and_deploy_job:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}   # exposes env-scoped secrets for this job

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Build
        run: npm run build

      - name: Install Azure SWA CLI
        run: npm install -g @azure/static-web-apps-cli

      - name: Deploy to ${{ inputs.swa_deploy_env }}
        run: |
          swa deploy ./dist \
            --deployment-token "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_DUNE_0565BA100 }}" \
            --env ${{ inputs.swa_deploy_env }}