name: Azure Static Web Apps CI/CD

on:
  workflow_dispatch:
    inputs:
      swa_deploy_env:             # SWA deploy lane: production | preview
        description: 'SWA deployment environment target'
        required: true
        type: choice
        options:
          - production
          - preview

jobs: 
  call-build-and-deploy:
    name: Run Build and Deploy 
    uses: ./.github/workflows/build.yml
    with:
      environment: $environment
      swa_deploy_env: $swa_deploy_env
    secrets: inherit