name: Run SWA CI/CD

on:
  workflow_dispatch:
    inputs:
      environment:            
        description: 'Deployment environment target'
        required: true
        type: choice
        options:
          - development
          - production
      swa_deploy_env:            
        description: 'SWA application environment target'
        required: true
        type: choice
        options:
          - preview
          - production

jobs: 
  call-build-and-deploy:
    name: Run Build and Deploy 
    uses: ./.github/workflows/build.yml
    with:
      environment: ${{ inputs.swa_deploy_env }}
      swa_deploy_env: ${{ inputs.swa_deploy_env }}
    secrets: inherit